name: Release Develop
on:
  push:
    branches: test

permissions:
  id-token: write
  contents: read

jobs:
  call-cdn-upload:
    uses: ./.github/workflows/cdn-upload.yml
    secrets:
      aws_role: ${{ secrets.awsIAMS3UploadDevRole }}
    with:
      target: "dev"
